### ISSUE TITLE
Add default font icons

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/brei-sass-boilerplate#18]
Use icomoon to generate default set of icons.

Ideas:
- social icons (facebook, twitter, youtube, etc)
-- They should be simple, e.g. no circles, borders, etc. Just the plain icon.
- House (for breadcrumbs)
- Menu (three lines)
- plus
- minus
- greater than/less than

**Comment by nessthehero** [comment]
We can use font awesome icons for this but it has to be through icomoon. I would rather only include what we need than to use the massive weight that the entire font awesome library adds.

**Comment by gabrielmedina** [comment]
I like the ionicons.com

**Comment by nessthehero** [comment]
Those are nice! Thanks!

**Comment by nessthehero** [comment]
This is essentially completed in the next branch.
