### ISSUE TITLE
Update _forms.scss selectors to match Foundation input types

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/brei-sass-boilerplate#40]
Currently, we are missing a few input types from here that are being used in Foundation's default form styles. We should include:

input[type='text']
input[type='password']
input[type='date']
input[type='datetime']
input[type='datetime-local']
input[type='month']
input[type='week']
input[type='email']
input[type='number']
input[type='search']
input[type='tel']
input[type='time']
input[type='url']
input[type='color']

**Comment by nessthehero** [comment]
What do these need added to? What selector group in that file?
