### ISSUE TITLE
Add helper .sccs file for Google Search overrides

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/brei-sass-boilerplate#44]
_From @sharissis-brei on June 20, 2016 20:21_

I suggest adding a file in the helpers for overwriting Google Search styles. Ideally, the file would also be configured to be exempt from scsslint so we can use things like !important, etc.

_Copied from original issue: BarkleyREI/generator-brei-app#183_

**Comment by nessthehero** [comment]
I'm gonna move this to the sass boilerplate repo.

**Comment by sharissis-brei** [comment]
Closing since GCSE is being phased out.
